stages:
  - build_and_push

variables:
  DOCKER_HUB_BACKEND_REPO: "ariru/trailtorchbackend"
  DOCKER_HUB_FRONTEND_REPO: "ariru/trailtorchfrontend"
  DOCKER_BACKEND_TAG: "backend"
  DOCKER_POSTGIS_TAG: "postgis"
  DOCKER_FRONTEND_TAG: "frontend"

build_and_push:
  stage: build_and_push
  script:
    # Build and push backend
    - docker build -t $DOCKER_HUB_BACKEND_REPO:$DOCKER_BACKEND_TAG -f path/to/your/backend/Dockerfile .
    - docker build -t $DOCKER_HUB_BACKEND_REPO:$DOCKER_POSTGIS_TAG -f path/to/your/postgis/Dockerfile .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_HUB_BACKEND_REPO:$DOCKER_BACKEND_TAG
    - docker push $DOCKER_HUB_BACKEND_REPO:$DOCKER_POSTGIS_TAG

    # Build and push frontend
    - docker build -t $DOCKER_HUB_FRONTEND_REPO:$DOCKER_FRONTEND_TAG -f path/to/your/frontend/Dockerfile .
    - docker push $DOCKER_HUB_FRONTEND_REPO:$DOCKER_FRONTEND_TAG
  only:
    - main  # Trigger this pipeline only for changes in the master branch
