build_and_push_frontend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t ariru/trailtorchfrontend:$TAG_FRONTEND -f frontend/Dockerfile frontend
    - docker push ariru/trailtorchfrontend:$TAG_FRONTEND
  only:
    - main  # Adjust the branch if needed
