include:
  - local: ci/build.yml
  - local: ci/deploy.yml
  - local: ci/backup_database.yml
  - local: ci/sonarqube.yml
  - local: ci/terraform.yml

stages:
  - build
  - deploy
  - backup_database
  - deploy_backend
  - deploy_frontend
  - terraform_validate
  - terraform_plan
  - terraform_apply
  - terraform_destroy


   
