include:
  - local: ci/build.yml
  - local: ci/deploy.yml
  - local: ci/backup_database.yml
  - local: ci/sonarqube.yml


stages:
  - build
  - deploy
  - backup_database
  - deploy_backend
  - deploy_frontend









