include:
  - local: ci/build.yml
  - local: ci/deploy.yml
  - local: ci/backup_database.yml

stages:
  - build
  - deploy
  - backup_database
  - deploy_backend
  - deploy_frontend

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonarcloud-check:
  stage: build  # Assigning the job to the 'build' stage
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop
    - main
