build_and_push_frontend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t ariru/trailtorchfrontend:latest -f frontend/Dockerfile frontend
    - docker push ariru/trailtorchfrontend:latest
  only:
    - main  # Adjust the branch if needed
