version: '3.8'
services:
    backend:
        image: weatherapp_backend:latest
        container_name: backend
        build:
            dockerfile: Dockerfile.backend
            context: ./backend
        environment:
            APPID: ${APPID}
            MAP_ENDPOINT: "http://api.openweathermap.org/data/2.5"
            
        ports:
            - "9000:9000"
        volumes:
        - ./backend/src:/usr/src/app/src

    frontend:
        image: weatherapp_frontend:latest
        container_name: frontend
        build:
            dockerfile: Dockerfile.frontend
            context: ./frontend
        environment:
            MAPID: ${MAPID}
           

        ports:
            - "8000:8000"
        volumes:
        - ./frontend/src:/usr/src/app/src
        depends_on:
            - backend

