version: '3.8'

services:
  postgres:
    image: postgis/postgis:latest
    env_file:   
      - .env    
    volumes:
      - ./geodata.sql:/docker-entrypoint-initdb.d/geodata.sql
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend  # Specify the Dockerfile name if not the default
    depends_on:
      - postgres
    env_file:   
      - .env
    ports:
      - "9000:9000"
