version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - .env
    volumes:
      - ./geodata.sql:/docker-entrypoint-initdb.d/geodata.sql
    ports:
      - "5432:5432"
    image: postgres  # Set the image name for the postgres service

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "9000:9000"
    image: backend  # Set the image name for the backend service
