#build and push backend

build_and_push_backend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd backend
    - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
    - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
    - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
    - echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
    - echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
    - echo "APPID=$APPID" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env
    
    - cat .env
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD

  script:
    - docker-compose -f docker-compose-prod.yml build # Build and start services
    - docker tag postgres:latest ariru/trailtorchbackend:postgis-latest  # Tag postgis image
    - docker push ariru/trailtorchbackend:postgis-latest  # Push postgis image to registry
    - docker tag backend:latest ariru/trailtorchbackend:backend-latest  # Tag backend image
    - docker push ariru/trailtorchbackend:backend-latest  # Push backend image to registry

  artifacts:
    paths:
      - docker-compose-dev.yml  # Add docker-compose-dev.yml as an artifact
  only:
    - main


# build_and_push_frontend:

build_and_push_frontend:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd frontend
    - echo "VITE_MAPBOX_TOKEN=$VITE_MAPBOX_TOKEN" >> .env
    - echo "VITE_BACKEND_URL=$VITE_BACKEND_URL" >> .env 
    - echo "VITE_RECAPTCHA=$VITE_RECAPTCHA" >> .env
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t ariru/trailtorchfrontend:latest -f Dockerfile.frontend-prod .
    - docker push ariru/trailtorchfrontend:latest
  only:
    - main